package com.sap.cap.cds.intellij.usersettings;

import com.intellij.openapi.components.Service;
import com.intellij.openapi.project.Project;

import java.util.HashMap;
import java.util.Map;

@Service(Service.Level.PROJECT)
public class CdsUserSettings {

    private final Project project;

    public CdsUserSettings(Project project) {
        this.project = project;
    }

    public static CdsUserSettings getInstance(Project project) {
        return project.getService(CdsUserSettings.class);
    }

    public Map<String, Object> getAllSettings() {
        // NOTE: method body is generated by patchUserSettingsJavaSrc.js
        Map<String, Object> defaults = new HashMap<>();
        defaults.put("placeholder", "value");
        return defaults;
    }
}
