name: gradle-run
description: Build the plugin using gradle

inputs:
  steps:
    description: 'The run steps to perform'
    required: true

runs:
  using: composite

  steps:
    - name: Install fontconfig
      # required for headless gradle
      run: |
        apt-get -y update
        apt-get -y install fontconfig
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21

    - name: Test
      if: ${{ contains(inputs.steps, 'test') }}
      shell: bash
      run: |
        ./gradlew test --info --stacktrace --no-daemon

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: ${{ contains(inputs.steps, 'test') }}
      with:
        name: test-results
        path: ./build/test-results/test

    - name: Build
      if: ${{ contains(inputs.steps, 'build') }}
      shell: bash
      run: |
        ./gradlew verifyPlugin buildPlugin --info --stacktrace --no-daemon
        ls -la build/distributions

    - name: Publish
      if: ${{ contains(inputs.steps, 'publish') }}
      shell: bash
      run: |
        ./gradlew publishPlugin --info --no-daemon
