name: gradle-run
description: Build the plugin using gradle

inputs:
  steps:
    description: 'The run steps to perform'
    required: true

runs:
  using: composite

  steps:
    - name: Debug Environment
      shell: bash
      run: |
        echo "Current User: $(whoami)"
        echo "Home Directory: $HOME"
        echo "Gradle User Home: ${GRADLE_USER_HOME:-$HOME/.gradle}"

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches/modules-2
          ~/.gradle/caches/build-cache-1
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-


    - name: Test
      if: ${{ contains(inputs.steps, 'test') }}
      shell: bash
      run: |
        ./gradlew test --info

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: ${{ contains(inputs.steps, 'test') }}
      with:
        name: test-results
        path: ./build/test-results/test

    - name: Build
      if: ${{ contains(inputs.steps, 'build') }}
      shell: bash
      run: |
        ./gradlew verifyPlugin buildPlugin
        ls -la build/distributions

    - name: Publish
      if: ${{ contains(inputs.steps, 'publish') }}
      shell: bash
      run: |
        ./gradlew publishPlugin --info
