name: gradle-run
description: Build the plugin using gradle

inputs:
  steps:
    description: 'The run steps to perform'
    required: true

runs:
  using: composite

  steps:
    - name: Install fontconfig
      # required for headless gradle
      run: |
        apt-get -y update
        apt-get -y install fontconfig
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21


    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          /root/.gradle/caches/modules-2
          /root/.gradle/caches/build-cache-1
          /root/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle', 'gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Debug cache size
      run: |
        [[ -d /root/.gradle ]] && find /root/.gradle -type f -exec du -h {} + | sort -rh | head -n 100 || true
      shell: bash

    - name: Test
      if: ${{ contains(inputs.steps, 'test') }}
      shell: bash
      run: |
        ./gradlew test --info --no-daemon

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: ${{ contains(inputs.steps, 'test') }}
      with:
        name: test-results
        path: ./build/test-results/test

    - name: Build
      if: ${{ contains(inputs.steps, 'build') }}
      shell: bash
      run: |
        ./gradlew verifyPlugin buildPlugin --no-daemon
        ls -la build/distributions

    - name: Publish
      if: ${{ contains(inputs.steps, 'publish') }}
      shell: bash
      run: |
        ./gradlew publishPlugin --info --no-daemon

    - name: Keep only small files for caching, which are faster to compress than to download
      run: |
        # Good thresholds as per measurement: currently 500 kB, more future-proof 900 kB.
        # Reason for latter: request duration dominated by ~constant request overhead, but compression time to decrease. 
        # Measurements: cache size (uncompr.) 1800 MB, compr. time 230 s, restoration time 6 s
        # Assumptions: req. overhead 60 ms, current download rate 110 MB/s
        find /root/.gradle/caches/modules-2     -type f -size +900k -delete
        find /root/.gradle/caches/build-cache-1 -type f -size +900k -delete
        find /root/.gradle/wrapper              -type f -size +900k -delete
      shell: bash
