name: upload-installable-zip
description: Upload build results as a ZIP directly installable in IntelliJ (equivalent to the ZIP built by Gradle)

# Prerequisites: gradle-run with step build must have run before this action

inputs:
  retention-days:
    description: 'The number of days to retain the artifact'
    required: false
    default: '14'

runs:
  using: composite

  steps:
    - name: Install Unzip
      shell: bash
      # apt-get update should have run elsewhere
      run: apt-get install unzip -y

    - name: Extract Zip
      shell: bash
      run: |
        mkdir extracted
        unzip build/distributions/cds-intellij.zip -d extracted

    - name: Upload Extracted Files as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cds-intellij
        path: extracted/
        retention-days: ${{ inputs.retention-days }}