name: Build and Test

on:
  workflow_dispatch:

concurrency:
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/gradle-run
        with:
          steps: |-
            test
            build
            test

      - uses: ./.github/actions/upload-installable-zip
