name: Build and Test

on:
  workflow_dispatch:

concurrency:
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/gradle-run
        with:
          steps: |-
            build
            test

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build results
          path: build/distributions/intellij-cds.zip
          compression-level: 0
          retention-days: 10
