name: Build and Test

on:
  workflow_dispatch:

concurrency:
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/prepare-cds-lsp-local
        with:
          gh_pat: ${{ secrets.GH_PAT_READ_PUBLIC_REPOS }}

      - uses: ./.github/actions/gradle-run
        with:
          steps: |-
            test
            build

      - uses: ./.github/actions/upload-installable-zip
