name: Main

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main-build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/gradle-run
        with:
          steps: |-
            test
            build

      - uses: ./.github/actions/upload-installable-zip
        with:
          retention-days: 7
